pois_file: configs/default/pois.yaml
spawn_points_file: configs/one_agent/spawn_points.yaml
start_time: '12:00'
speed_multiplier: 50
time_density: 1
pixels_per_meter: 1.5
heatmap_multiplier: 2
DEBUG: False
DEBUG_SCHEDULER: TRUE