mean_age: 37 #In Krak贸w: 37
domestic: 0.7 #fraction of domestic tourists, in Krak贸w: 0.7
education: 5 # percentage of people with higher education scaled 0-10, in Krak贸w: 53
mean_wealth: 7 # percentage of people who identify as wealthy scaled 0-10, in Krak贸w: 7
