pois_file: configs/default/pois.yaml
spawn_points_file: configs/default/spawn_points.yaml
start_time: '12:00'
speed_multiplier: 25
time_density: 1
pixels_per_meter: 1.5
heatmap_multiplier: 1.5
DEBUG: True
DEBUG_SCHEDULER: False