Teatr Bagatela:
    x: -990
    y: 1300
    agents_per_min: 0.4
    bus_frequency: 50
    bus_average_number_of_passengers: 8

Filharmonia:
    x: -900
    y: 540
    agents_per_min: 0.3
    bus_frequency: 40
    bus_average_number_of_passengers: 6

Plac Wszystkich Swietych:
    x: -430
    y: 555
    agents_per_min: 0.3
    bus_frequency: 40
    bus_average_number_of_passengers: 8

Poczta Glowna:
    x: 35
    y: 625
    agents_per_min: 0.2
    bus_frequency: 65
    bus_average_number_of_passengers: 6

Dworzec Glowny:
    x: 350
    y: 1450
    agents_per_min: 0.2
    bus_frequency: 70
    bus_average_number_of_passengers: 9

Stary Kleparz:
    x: -270
    y: 1750
    agents_per_min: 0.3
    bus_frequency: 85
    bus_average_number_of_passengers: 5
    