Teatr Bagatela:
    x: -990
    y: 1300
    agents_per_min: 0.5
    
Filharmonia:
    x: -900
    y: 540
    agents_per_min: 0.1
    
Plac Wszystkich Swietych:
    x: -430
    y: 555
    agents_per_min: 0.2
    
Poczta Glowna:
    x: 35
    y: 625
    agents_per_min: 0.3
    
Dworzec Glowny:
    x: 350
    y: 1450
    agents_per_min: 0.3
    
Stary Kleparz:
    x: -270
    y: 1750
    agents_per_min: 0.05
    